"""add missing columns to module_progress

Revision ID: 000c9060865e
Revises: 28244997e440
Create Date: 2026-06-24 19:33:51.845220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000c9060865e'
down_revision: Union[str, Sequence[str], None] = '28244997e440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_progress', sa.Column('started_at', sa.String(), nullable=True))
    op.add_column('module_progress', sa.Column('time_spent_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_progress', 'time_spent_seconds')
    op.drop_column('module_progress', 'started_at')
    # ### end Alembic commands ###
