"""add default_sop_path and welcome_attachments columns

Revision ID: c53408c87cd7
Revises: 54714ede33c6
Create Date: 2026-08-24 07:25:51.552941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c53408c87cd7'
down_revision: Union[str, Sequence[str], None] = '54714ede33c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_settings', sa.Column('default_sop_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('welcome_attachments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'welcome_attachments')
    op.drop_column('email_settings', 'default_sop_path')
    # ### end Alembic commands ###
